### ISSUE TITLE
Needed to maintain listing in k6 Extensions Registry

### ISSUE THREAD

**Issue by javaducky** [kubeshop/xk6-tracetest#2]
### What happened?

We've recently updated the requirements for maintaining an extension within the listing on our site. As such, please address the following items to maintain your listing within the registry:

* add the xk6 topic to your repository metadata
* add an `examples` directory containing k6 test scripts making use of your extension
* needs to build with a recent version of k6; minimum v0.43

For more information on these and other listing requirements, please take a look at the [registry requirements](https://k6.io/docs/extensions/explanations/about-the-extensions-registry/).

### Version

1.0.0 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kdhamric** [comment]
@xoscar Could you either take care of this or ask somebody to?

**Comment by xoscar** [comment]
@kdhamric sure thing I'll take a look

**Comment by xoscar** [comment]
Hello @javaducky thanks for letting us know and opening the issue.

Is there a sample extension that has been already updated and approved by you so I can base my work on that? thanks!

**Comment by javaducky** [comment]
Hola @xoscar! 

https://github.com/elastic/xk6-output-elasticsearch is a repo that recently addressed similar issues. 

* Update `go.mod` for a more recent k6 version (v0.45.0 is latest, and update to Go 1.19 to match)
* Rename the `tests` directory to `examples` (your README even refers to examples as the directory)
* Last is a setting on your repository to add the `xk6` label (this allows us to search GitHub for extensions)

We're looking for consistency across all extensions so we can create automation to verify extensions we're listing haven't gone stale.

**Comment by javaducky** [comment]
@xoscar, with the changes provided by #3, the only remaining item would be to update the metadata for the repository by adding the `xk6` label.

**Comment by xoscar** [comment]
Hey @javaducky all done, thanks for helping us with those changes!

**Comment by javaducky** [comment]
Thanks @xoscar! You'll probably want to cut a release soon as well so anyone using the extension with `latest` will be using the latest version of k6.
